### PR TITLE
53 workflow for improved templates in yml luiza 00

### LINKED ISSUE #53: Workflow for improved templates in yml
# STORY
- [x] #51 

# Description

### PR DESCRIPTION
**Pull request by ziliolu**
## Description
This pull request introduces new issue and pull request templates to improve the process of creating and managing issues and pull requests. The main changes include the addition of detailed templates for epics, stories, and tasks, as well as a comprehensive pull request template.

### Issue Templates:

* Added a new template for creating detailed epics with sections for description, stories, priority, and related epics. (`.github/ISSUE_TEMPLATE/epic-template.yml`)
* Added a new template for creating detailed stories with sections for description, epic reference, tasks, and priority. (`.github/ISSUE_TEMPLATE/story-template.md`)
* Added a new template for creating detailed tasks with sections for description, story reference, and priority. (`.github/ISSUE_TEMPLATE/task-template.md`)

### Pull Request Template:

* Added a new pull request template to ensure consistent and comprehensive information is provided, including sections for description, type of change, checklist, related issues, and additional context. (`.github/pull_request_template.md`)

### Removal of Old Templates:

* Removed outdated templates for creating epic, story, and task issues. (`.github/ISSUE_TEMPLATE/epic-issue-create.md`, `.github/ISSUE_TEMPLATE/story-issue-create.md`, `.github/ISSUE_TEMPLATE/task-issue-create.md`) [[1]](diffhunk://#diff-2751a7d7de3e73f3552503310c05ce7fd72de74b46620a685a64acb65e9a88cdL1-L15) [[2]](diffhunk://#diff-6e48d4711536949726fb5afd69901062eb035f2639a007c5c658af4c469490e9L1-L19) [[3]](diffhunk://#diff-a0f773527300e345bf09ab58112780cffb104ce2d562cdea0e59f1630c01abbdL1-L14)

## Type of Change
- [ ] 🐞 Bugfix (fixes an issue)
- [ ] ✨ New Feature (introduces new functionality)
- [ ] 📄 Documentation (adds or updates documentation)
- [x] 🔧 Configuration (adjusts project configuration or tooling)

## Checklist
- [ ] Code is thoroughly tested and operates as expected
- [ ] Documentation has been updated to reflect these changes (if applicable)
- [x] No breaking changes introduced

## Additional Context

---

### Reviewer Checklist
- [ ] Code follows project style and naming conventions.
- [ ] No functionality is broken; code is well-tested.
- [ ] Documentation and comments are clear.
- [ ] No security vulnerabilities or performance issues are introduced.

### CODE REVIEW

**Comment by luis-ffe** [comment]
This pull request focuses on updating and improving the issue and pull request templates. The changes include replacing old templates with new, more detailed ones and adding a new pull request template to standardize contributions.

### Updates to issue templates:

* **Epic Issue Template**: Replaced the old `epic-issue-create.md` with a new `epic-template.yml` that includes detailed fields for description, stories, priority, and related epics. [[1]](diffhunk://#diff-2751a7d7de3e73f3552503310c05ce7fd72de74b46620a685a64acb65e9a88cdL1-L15) [[2]](diffhunk://#diff-3ddf7ebf516fca23038f72a2faaf73b9e98d0150bf211907572bd6efd5862669R1-R58)
* **Story Issue Template**: Replaced the old `story-issue-create.md` with a new `story-template.md` that includes fields for description, epic reference, tasks, and priority. [[1]](diffhunk://#diff-6e48d4711536949726fb5afd69901062eb035f2639a007c5c658af4c469490e9L1-L19) [[2]](diffhunk://#diff-bdb7fae38de8fb1a4c77f313b10c10da0e2871acd7ef57e0d77f1119cc8ac82fR1-R58)
* **Task Issue Template**: Replaced the old `task-issue-create.md` with a new `task-template.md` that includes fields for description, story reference, and priority. [[1]](diffhunk://#diff-a0f773527300e345bf09ab58112780cffb104ce2d562cdea0e59f1630c01abbdL1-L14) [[2]](diffhunk://#diff-986f13eba6b88b6c640e1860ea817c1fa461414f9457e1c4f84e858bdce45643R1-R49)

### Addition of pull request template:

* **Pull Request Template**: Added a new `pull_request_template.md` to standardize the submission of pull requests, including sections for description, type of change, checklist, related issues, and additional context.

**Review by Rui-Pedro-Pires — APPROVED** [review]
### Reviewer Checklist
- [x] Code follows project style and naming conventions.
- [x] No functionality is broken; code is well-tested.
- [x] Documentation and comments are clear.
- [x] No security vulnerabilities or performance issues are introduced.

**Review by luis-ffe — COMMENTED** [review]
### Reviewer Checklist
- [x] Code follows project style and naming conventions.
- [x] No functionality is broken; code is well-tested.
- [x] Documentation and comments are clear.
- [x] No security vulnerabilities or performance issues are introduced.

**Review by luis-ffe — APPROVED** [review]
### Reviewer Checklist
- [x] Code follows project style and naming conventions.
- [x] No functionality is broken; code is well-tested.
- [x] Documentation and comments are clear.
- [x] No security vulnerabilities or performance issues are introduced.

**Pull request merged**
